156814049 user menu toolbar
Videona/platform-frontend pull request #60
Opened 2018-04-25 14:44 UTC by CodingCarlos

2018-04-26 10:49 UTC, DevStarlight approved these changes

2018-04-27 14:14 UTC, javierLiarte requested changes
Seems too much unnecessary work to reimplement a menu using a panel and a list instead of using material mdMenu directive, I upload a PR with suggested changes

Also translations for menu items are missing :S

2018-04-27 14:14 UTC, javierLiarte commented on components/profile-top-menu/dialog.html
> +	<md-list-item class="profile-top-menu-item no-pointer" role="option">
So... why don't use material library mdMenu directive that provides a menu, instead of reimplementing a menu? :m

2018-04-27 14:14 UTC, javierLiarte commented on components/profile-top-menu/dialog.html
> +		<span>Mis videos</span>
missing translation

2018-04-27 14:14 UTC, javierLiarte commented on components/profile-top-menu/dialog.html
> +		<span>Logout</span>
missing translation

2018-04-27 14:14 UTC, javierLiarte commented on components/profile-top-menu/profile-top-menu.view.html
> +	<i ng-if="session.id > -1 && !Video.user.data.pic" ng-click="switch();" class="material-icons">person_pin</i>
where this pic is supposed to come from? if this actually work, it seems that will display current viewd video owner pic, and not logged in user pic, so I think it should be stored in session object once user backend model has pic field

2018-04-27 14:14 UTC, javierLiarte commented on pages/upload/upload.controller.js
> +		$state.go('signin');
:+1:

2018-04-30 08:02 UTC, merged